### ISSUE TITLE
`TypeError: node.identity.split is not a function`

### ISSUE THREAD

**Issue by joelmoss** [ioquatix/sus-vscode#1]
Installed the extension on latest vscode, and when I refresh the tests, I get this in the log...

```
2023-03-14 15:10:41.974 [error] TypeError: node.identity.split is not a function
	at Project.addNode (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/out/sus.js:24:37)
	at Project.addNodes (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/out/sus.js:19:29)
	at Project.updateTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/out/sus.js:37:28)
	at Project.loadTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/out/sus.js:66:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async r.$refreshTests (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:142948)
2023-03-14 15:10:42.446 [error] TypeError: Cannot read properties of undefined (reading 'parent')
	at l.fromExtHostTestItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:1216)
	at h.isIncluded (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:149076)
	at Object.started (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:145469)
	at Runner.onData (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/out/runner.js:113:26)
	at Transform.emit (node:events:526:28)
	at addChunk (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_readable.js:298:12)
	at readableAddChunk (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_readable.js:280:11)
	at Readable.push (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_readable.js:241:10)
	at Transform.push (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_transform.js:139:32)
	at push (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/split2/index.js:73:10)
	at Transform.transform [as _transform] (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/split2/index.js:44:7)
	at Transform._read (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_transform.js:177:10)
	at Transform._write (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_transform.js:164:83)
	at doWrite (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_writable.js:409:139)
	at writeOrBuffer (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_writable.js:398:5)
	at Writable.write (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.3.0/node_modules/readable-stream/lib/_stream_writable.js:307:11)
	at Socket.ondata (node:internal/streams/readable:754:22)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by ioquatix** [comment]
Hmm, thanks, I'll take a look.

**Comment by joelmoss** [comment]
FYI, I still get this error on 0.0.50...

```
2023-06-13 22:22:21.662 [info] ExtensionService#_doActivateExtension socketry.sus-vscode, startup: false, activationEvent: 'workspaceContains:config/sus.rb'
2023-06-13 22:22:23.111 [error] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadTreeFromPath (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/tree.ts:85:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Project.loadTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:140:16)
    at Project.setup (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:179:3)
    at addProject (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/extension.ts:19:4)
2023-06-13 22:22:25.053 [error] TypeError: node.identity.split is not a function
    at Project.addNode (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:116:31)
    at Project.addNodes (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:101:21)
    at Project.updateTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:136:8)
    at Project.loadTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:142:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Project.setup (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:179:3)
    at addProject (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/extension.ts:19:4)
```

**Comment by ioquatix** [comment]
For the latter error, does `bundle exec sus-tree` generate valid JSON?

**Comment by ioquatix** [comment]
I noticed that VSCode doesn't always pick up the environment. If you run `ruby --version` in VSCode do you get the correct version of Ruby?

**Comment by joelmoss** [comment]
Yes, and yes. 

```
❯ ruby --version                      
ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin22]
```

**Comment by ioquatix** [comment]
Normally what is happening, is `sus-vscode` is trying to run `bundle exec sus-tree` and it's printing out an error, which it's trying to parse as JSON.

Can you try completely exiting VSCode, then go to the project directory in the terminal, and start VSCode from that directory, e.g. `code .` and then confirm the problem persists?

**Comment by joelmoss** [comment]
Same error, although only the following (so not `SyntaxError: Unexpected end of JSON input`)

```
[error] TypeError: node.identity.split is not a function
    at Project.addNode (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:116:31)
    at Project.addNodes (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:101:21)
    at Project.updateTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:136:8)
    at Project.loadTree (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:142:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Project.setup (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/sus.ts:179:3)
    at addProject (/Users/joelmoss/.vscode/extensions/socketry.sus-vscode-0.5.0/src/extension.ts:19:4)
```

Took a little look at the extension, and noticed at https://github.com/ioquatix/sus-vscode/blob/main/src/tree.ts#L64 it is loading the `self` node of the JSON, which for my current project is

```js
> json['self']
[
  {
    path: '/Users/joelmoss/dev/clients/harleytherapy/hue',
    name: null,
    line: null,
    parent: null,
    unique: true,
    key: null
  },
  {
    base: null,
    loaded: {
      'test/hue/components/badge.rb': null,
      'test/hue/components/breadcrumbs.rb': null,
      'test/hue/components/button_to.rb': null,
      'test/hue/components/checkbox_field.rb': null,
      'test/hue/components/description_list.rb': null,
      'test/hue/components/form/fields/basic_inputs.rb': null,
      'test/hue/components/form/fields/checkbox.rb': null,
      'test/hue/components/form/fields/date.rb': null,
      'test/hue/components/form/fields/radio.rb': null,
      'test/hue/components/form/fields/rich_textarea.rb': null,
      'test/hue/components/form/fields/select.rb': null,
      'test/hue/components/form.rb': null,
      'test/hue/components/icon.rb': null,
      'test/hue/components/lib/button.rb': null,
      'test/hue/components/lib/sheet.rb': null,
      'test/hue/components/table.rb': null,
      'test/hue/components/tabs.rb': null,
      'test/hue/version.rb': null,
      'test/validators/unique_range_validator.rb': null
    }
  },
  false
]
```

The code expects an array of three elements (`const [identity, description, leaf] = json['self'];`), which is what we have. And it passed those three vars to `Node` at https://github.com/ioquatix/sus-vscode/blob/main/src/tree.ts#L30

But according to the types, it expects both `identity` and `description` to be strings, which they are not. They are both objects.

So looks to me naive eyes to be incorrect data in the json from `sus-tree`?

**Comment by joelmoss** [comment]
I think I may have found the cause of `SyntaxError: Unexpected end of JSON input` though. I have a VSCode workspace that contains two directories at the root:

```json
{
  "folders": [
    {
      "path": "project1"
    },
    {
      "path": "project2"
    }
  ],
  "settings": {}
}
```

So I would guess that when the extension attempts to call `sus-tree` that it is failing due to the lack of a definitive root directory for the workspace.

**Comment by ioquatix** [comment]
Is there a chance you can share this repo with me? Also are you using the latest version of `sus`?

**Comment by joelmoss** [comment]
I'm using the latest (0.21.0). No its a private project, sorry.

**Comment by ioquatix** [comment]
Can you share the entire output of `sus-tree`? There shouldn't be any private data in there, just a bunch of file paths. Feel free to make a private gist.

**Comment by ioquatix** [comment]
Here is the normal output of the tree, for the Node:

```json
{
  "self": [
    "test/sus/have.rb:37",
    "Array",
    false
  ],
  "children": [
    {
      "self": [
        "test/sus/have.rb:40",
        "can contain a value",
        true
      ]
    },
    {
      "self": [
        "test/sus/have.rb:46",
        "reports a single failure",
        true
      ]
    },
    {
      "self": [
        "test/sus/have.rb:53",
        "doesn't contain a value",
        true
      ]
    }
  ]
}
```

It looks odd that those fields are not strings. Let me see if I can figure out how that's being generated.

**Comment by joelmoss** [comment]
https://gist.github.com/joelmoss/c8b5bfe13919ebf973a6a55f05988318

**Comment by joelmoss** [comment]
Ok, so the `children` node looks right then. It's the root `self` that is not in the correct format.

**Comment by ioquatix** [comment]
What does your `config/sus.rb` contain?

**Comment by ioquatix** [comment]
Yes, the root node is wrong, it looks like it's dumping the whole registry instead of the base class (for tests).

**Comment by ioquatix** [comment]
I'm just trying to figure out how that is even possible... dumping the registry.

**Comment by ioquatix** [comment]
Is anything in your code overriding `identity` or `def identity` or are you pulling in any gems that modify `sus`?

**Comment by ioquatix** [comment]
Ohhhhh, I have an idea...

Can you show me your gem lock file?

**Comment by ioquatix** [comment]
Got it...

```
> bundle exec sus-tree | jq | head
{
  "self": [
    {
      "path": "/Users/samuel/Developer/ioquatix/sus-vscode/sus",
      "name": null,
      "line": null,
      "parent": null,
      "unique": true,
      "key": null
    },
```

was able to reproduce it.

**Comment by joelmoss** [comment]
What should be the base class?

**Comment by ioquatix** [comment]
Can you try sus v0.21.1 - I believe it will fix the issue for you.

**Comment by joelmoss** [comment]
Yup! That worked! thx.

However, I still have the `SyntaxError: Unexpected end of JSON input` when using the workspace with two root directories:

```json
{
  "folders": [
    {
      "path": "project1"
    },
    {
      "path": "project2"
    }
  ],
  "settings": {}
}
```

Presumably because the extension doesn't know which directory to run in. Not sure how to fix that

**Comment by joelmoss** [comment]
Actually, no. I tell a lie 😏

That's also working now. Still get the error, but I assume that is because it fails in one directory, but not the other.

Anyway, thanks again.

**Comment by ioquatix** [comment]
Do you have tests in both directories or just one?

**Comment by joelmoss** [comment]
Just the one, which I assume is where the error is coming from. Does the command get run in both directories automatically?

**Comment by ioquatix** [comment]
I don't think I ever considered the precise activation of the extension, it just tries to run on every project directory/workspace. I should probably make something a bit more intelligent.

https://github.com/ioquatix/sus-vscode/blob/main/src/extension.ts
